"""Create URL table

Revision ID: bae845dbef93
Revises: 3ba35f229b9a
Create Date: 2023-12-31 20:10:46.843099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bae845dbef93"
down_revision: Union[str, None] = "3ba35f229b9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_urls_short_url_test_for_alembic", table_name="urls")
    op.drop_column("urls", "short_url_test_for_alembic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urls",
        sa.Column(
            "short_url_test_for_alembic",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        "ix_urls_short_url_test_for_alembic",
        "urls",
        ["short_url_test_for_alembic"],
        unique=False,
    )
    # ### end Alembic commands ###
